ros2_control:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints: [junta_0_1, junta_1_2, junta_2_3, junta_3_4, junta_4_5, junta_5_6]
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints: [junta_0_1, junta_1_2, junta_2_3, junta_3_4, junta_4_5, junta_5_6]
      gains: {}

    controllers:
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        parameters:
          publish_rate: 50
