# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - junta_0_1
      - junta_1_2
      - junta_2_3
      - junta_3_4
      - junta_4_5
      - junta_5_6
    command_interfaces:
      - position
    state_interfaces:
      - position
    controller_state_topic: "/arm_controller/controller_state"